name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome
        ports:
          - 4444:4444

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin' # Distribution can be 'adopt', 'zulu', 'temurin', etc.
        java-version: '11'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Install dependencies
      run: ./gradlew clean assemble

    - name: Run API tests
      run: ./gradlew test --tests *ApiTest*

    - name: Run UI tests
      run: ./gradlew test --tests *UiTest*

    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: build/test-results/test

    - name: Deploy to GitHub Pages
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/reports/tests/test
